### activate
POST http://127.0.0.1:8000/api/v1/accounts/otp-send/
Content-Type: application/json

{
    "email": "student3@gmail.com"
}

### verify
POST http://127.0.0.1:8000/api/v1/accounts/otp-verify/
Content-Type: application/json

{
    "email": "student1@gmail.com",
    "otp": "759228"
}

### login
POST http://127.0.0.1:8000/api/v1/accounts/login/
Content-Type: application/json

{
    "email": "student1@gmail.com",
    "password": "student333"
}


### profile
GET http://127.0.0.1:8000/api/v1/accounts/profile/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM0OTg0MzUwLCJpYXQiOjE3MzQ5ODA3NTAsImp0aSI6IjUxYjc1NzgxMDE0NDQzNjRiODcyMDhkOWIwMTA1OThmIiwidXNlcl9pZCI6MX0.hKHoPrzL0nFeEzGB89N_jZmVEYXYa4JIg3aLHNRNRR4


### update
PUT http://127.0.0.1:8000/api/v1/accounts/update/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM1MDQ1NjY4LCJpYXQiOjE3MzUwNDIwNjgsImp0aSI6ImEyMDhjZjFlM2Q4NjQ1ZjE4NzUzZTNjOTUxZTg0MmIyIiwidXNlcl9pZCI6Mn0.2LbbDkZrtTGcahg2z_Zs5WCuqRrQ6l1HRlfHD4kK-Pw

{
    "name": "student1",
    "email": "student1@gmail.com",
    "role": "student",
    "bio": "I am student"
}

### change password
PUT http://127.0.0.1:8000/api/v1/accounts/password/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM1MDUzNTE3LCJpYXQiOjE3MzUwNDk5MTcsImp0aSI6ImEyY2NiN2E2ZjYzZDQ4YTM4YmVhN2Q3ODM0Yzg0NjFiIiwidXNlcl9pZCI6Mn0.BkoyDveBoFSIHPOBUsOFFLTbL_H8KVbxpiGI_o5nNdc

{
    "old_password": "password333",
    "new_password": "student333",
    "confirm_password": "student333"
}